### ISSUE TITLE
Order in Magento is not created anymore.

### ISSUE THREAD

**Issue by bitforbucket** [Nets-eCom/Magento2_easy#33]
Starting from 1.4.5 module version orders are not created in magento checkout before redirect to nets payments website happens. Because of this we get error message after we submit card information. 

After postback from nets website we get error: "We are sorry, but your order seems to have gone missing. Please contact customer support with Nets Payment ID:". Version 1.4.4 has no issues.

We are using checkout flow: redirect and magento 2.3.5 and nets playground test mode.

As I can see in vendor/nets/easycheckout/view/frontend/web/js/view/payment/method-renderer/checkout-method.js on line 38 ajax call to easycheckout/order/saveOrder to create order was commented out. Why?

**Comment by trolldev** [comment]
I would like to follow up if there is an update regarding the issue outlined below?

**Comment by Tim-Badin** [comment]
Hi @bitforbucket  and @trolldev 
Our team will conduct an assessment on this issue and revert back here.
Keep you posted!

**Comment by trolldev** [comment]
Hi @Tim-Badin, it's been a while since I heard from you, is there an update to your assessment?

**Comment by sursi** [comment]
Hi All,

The issue must be on localhost, as version 1.4.5 onwards the order gets created on the response from webhhok, on localhost we can not get response so it may not work please test on staging server.

The ajax call commented out because that is getting called from server side now.

If you are facing this issue on server can you please share temporary FTP access with us?

I hope this is helpful. Have a great day.


Sincerely,
Surjan

**Comment by bitforbucket** [comment]
@sursi order is not created also on stage, which postback controller is responsible now to create order in magento ?

**Comment by sursi** [comment]
Hi All,

The controller is controller/order/saveorder.php this controller gets called from the webhook event. If redirect flow is not working can you please check with Vanilla Embeded flow once?

Can we have temporary access to your website to investigate the issue for you?

Have a nice day.

Sincerely,
Surjan

**Comment by bitforbucket** [comment]
@sursi Embeded flow works, order is created in magento, It seems order is not created using "Redirect" flow which we need.

**Comment by sursi** [comment]
@bitforbucket 

Can we have temporary access to your website to investigate the issue for you?

Have a nice day.

Sincerely,
Surjan

**Comment by bitforbucket** [comment]
@sursi sorry we don't have ftp access and it is not possible to give you access at the moment. 

When this postback happens to create order in magento? POST to create order in magento should come from https://test.checkout.dibspayment.eu? I'm using ngrok but there are no saveOrder postback to controller/order/saveorder.php  from https://test.checkout.dibspayment.eu to magento. 

From https://test.checkout.dibspayment.eu it redirects directly to vendor/nets/easycheckout/Controller/Order/ConfirmOrder.php and fails because it can't find order in magento.

Is this correct test sandbox url: https://test.checkout.dibspayment.eu ?

**Comment by Skwecode** [comment]
Hi, 
Is there any update to this? It's still happening in the latest module version & causing me a headache. We're being forced to update the module because MobilePay orders fail 30-40% of the times. Even though the money is reserved, the order is never created. This is in version 1.4.3. 
With the latest version, 1.5.2, using the hosted payment gateway, no orders are being placed in my local setup or on our staging server. It doesn't matter if it's using mobilepay or a card payment.  

![Screenshot 2022-06-22 at 11 57 14](https://user-images.githubusercontent.com/70141130/175002169-6be721ca-69e9-423d-8448-b4e5c3f928b5.png)

Even though the documentation is mentioning that the order is now being placed before the redirect, i can't find anywhere where that's the case.

**Comment by sursi** [comment]
Hi @bitforbucket,

**Comment by vanexssa** [comment]
This error is happening at several clients, and sharing ftp access is not an option for many company - due to internal policies.

This issue is there since March.
Version 1.5.6: Fixed : Order gone missing issue.
but this is still encountered at version 1.5.7

Will you or have find a solution for this ? Thanks

**Comment by sursi** [comment]
Hi All,

We have fixed this issue and testing the scenario, can we have your email address to share module to test before the release?

If yes please provide us your email address or raise a ticket so that we can provide pre release module to test.

Have a nice day. 

Sincerely,
Surjan,
Nets

**Comment by Tim-Badin** [comment]
Ping @vanexssa  could you get in touch via email integration-plugin@nets.eu so that we can check the new build that @sursi  and team have released. 
Thank you

**Comment by sursi** [comment]
@bitforbucket, @vanexssa please get the beta version for the fix from here and let us know your feedback: https://github.com/Nets-eCom/Magento2_easy/releases/tag/1.5.8

**Comment by vanexssa** [comment]
@Tim-Badin @sursi We have recently upgrading to 1.5.8. We are conducting some tests, will keep you posted. Thanks

**Comment by vanexssa** [comment]
@Tim-Badin @sursi FYI as confirm with QA, the error is not encountered anymore

**Comment by sursi** [comment]
@vanexssa Thanks a lot for testing the module and letting us know that issue has been fixed.
The same version has been released to here and Magento marketplace, kindly reopen issue here or submit the ticket is you encounter any other or this issue in future.

We are closing this issue.

Thank you once again!

**Comment by vanexssa** [comment]
@Tim-Badin @sursi Do you encounter a latency of approximately 2-3mins to get the webhooks when switching to 1.5.8?
This wasn't encountered with earlier version

**Comment by sursi** [comment]
@vanexssa we are investigating the issue, is it for specific payment type or for all payment type?

**Comment by sursi** [comment]
@vanexssa can you please confirm if still facing delay?

will it be possible to share log files?
